packages:
  - apps/*
  - packages/*
overrides:
  '@expo/dom-webview': link:./packages/dom-webview
allowBuilds:
  esbuild: true
nodeLinker: hoisted
patchedDependencies:
  expo-dev-menu@57.0.18: patches/expo-dev-menu@57.0.18.patch
  expo-router@57.0.19: patches/expo-router@57.0.19.patch
  react-native-screens@4.26.2: patches/react-native-screens@4.26.2.patch
minimumReleaseAgeExclude:
  - '@rien7/anchored-overlay-kit@0.3.0'
